# Generated by Django 5.2.17 on 2026-09-02 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('current_odometer', models.PositiveIntegerField()),
                ('service_interval_days', models.PositiveIntegerField()),
                ('service_interval_km', models.PositiveIntegerField()),
                ('next_due_date', models.DateField(db_index=True, null=True)),
                ('next_due_odometer', models.PositiveIntegerField(db_index=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('BOOKED', 'Booked'), ('IN_SERVICE', 'In service'), ('COMPLETED', 'Completed')], db_index=True, max_length=20)),
                ('due_since', models.DateTimeField(null=True)),
                ('scheduled_date', models.DateField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('completed_odometer', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technicians', models.ManyToManyField(blank=True, related_name='assigned_service_records', through='fleet.ServiceAssignment', through_fields=('service_record', 'technician'), to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='fleet.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.servicerecord'),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status changed'), ('TECHNICIAN_ASSIGNED', 'Technician assigned'), ('TECHNICIAN_UNASSIGNED', 'Technician unassigned'), ('NOTE_ADDED', 'Note added')], max_length=32)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='fleet.servicerecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='serviceassignment',
            unique_together={('service_record', 'technician')},
        ),
        migrations.CreateModel(
            name='AlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.servicerecord')),
            ],
            options={
                'unique_together': {('service_record', 'dismissed_by')},
            },
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['status', 'due_since'], name='servicerecord_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_odometer__isnull', True)), models.Q(('completed_at__isnull', False), ('completed_odometer__isnull', False)), _connector='OR'), name='servicerecord_completed_fields_together'),
        ),
    ]
